# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means you cannot fetch it from the container via $container->get().

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    security.user.provider.oauth2:
        alias: security.user.provider.concrete.oauth2_provider
        public: true

    # App\Security\APIAuthenticator:
    #     arguments:
    #         $userProvider: '@security.user.provider.oauth2'

    League\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator:
        arguments:
            Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.oauth2_provider'
            $rolePrefix: 'ROLE_OAUTH2_'

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        alias: 'league.oauth2_server.factory.psr_http'

   
            
   
    # Register nyholm/psr7 services for autowiring with PSR-17 (HTTP factories)
    # Psr\Http\Message\RequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    # Psr\Http\Message\ResponseFactoryInterface: '@nyholm.psr7.psr17_factory'
    # Psr\Http\Message\ServerRequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    # Psr\Http\Message\StreamFactoryInterface: '@nyholm.psr7.psr17_factory'
    # Psr\Http\Message\UploadedFileFactoryInterface: '@nyholm.psr7.psr17_factory'
    # Psr\Http\Message\UriFactoryInterface: '@nyholm.psr7.psr17_factory'

    # nyholm.psr7.psr17_factory:
    #     class: Nyholm\Psr7\Factory\Psr17Factory

    # # Custom implementation of ServerRequestInterface
    # App\Service\Psr17ServerRequest:
    #     arguments:
    #         $psr17Factory: '@nyholm.psr7.psr17_factory'

    # Alias for ServerRequestInterface
    # Psr\Http\Message\ServerRequestInterface: '@App\Service\Psr17ServerRequest'

    # # Alias pour UserProviderInterface
    # Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.oauth2_provider'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
