# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # Service GitHub
    App\Service\GitHubService:
        arguments:
            $githubToken: '%env(GITHUB_TOKEN)%'
            $repoOwner: '%env(GITHUB_REPO_OWNER)%'
            $repoName: '%env(GITHUB_REPO_NAME)%'
            $branch: '%env(GITHUB_BRANCH)%'

    # Service Netlify 
    App\Service\NetlifyService:
        arguments:
            $httpClient: '@http_client'
            $params: '@parameter_bag'
            $logger: '@logger'
            $netlifyHookUrl: '%env(NETLIFY_BUILD_HOOK)%'
            


    # Service PortfolioDataService
    App\Service\PortfolioDataService: 
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $workRepository: '@App\Repository\WorkRepository'
            $skillRepository: '@App\Repository\SkillRepository'
            $languageRepository: '@App\Repository\LanguageRepository'
            $interestRepository: '@App\Repository\InterestRepository'
            $portfolioReferenceRepository: '@App\Repository\PortfolioReferenceRepository'
            $projectRepository: '@App\Repository\ProjectRepository'
            $profileRepository: '@App\Repository\ProfileRepository'
            $locationRepository: '@App\Repository\LocationRepository'
            $educationRepository: '@App\Repository\EducationRepository'
            $params: '@parameter_bag'

    # Déclarations des alias pour les interfaces globales de Symfony
    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'
    Psr\Log\LoggerInterface: '@logger'
    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@parameter_bag'

    League\Bundle\OAuth2ServerBundle\Security\Authenticator\OAuth2Authenticator:
        arguments:
            Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.oauth2_provider'
            $rolePrefix: 'ROLE_OAUTH2_'

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        alias: 'league.oauth2_server.factory.psr_http'